### ISSUE TITLE
Circular dependencies between prokaryote.MetabolismSubmodelGenerator and prokaryote.InitalizeModel

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_model_gen#14]
As currently implemented, if the kb defines any reactions or rate laws that use metabolites, then InitalizeModel should run gen_kb_reactions() and gen_kb_rate_laws() to build the corresponding lang reactions and rate laws. But these methods use the metabolism submodel, so InitalizeModel depends on MetabolismSubmodelGenerator which creates that submodel.

But MetabolismSubmodelGenerator.gen_reactions() uses species that get created by InitalizeModel.gen_metabolic_species(), thereby creating a circular dependency.

InitalizeModel is a good idea, but it shouldn't be creating reactions, rate laws or anything else that has a submodel as an attribute or depends on such a thing. It can create the Model, Compartments, SpeciesTypes, Concentrations, Functions, and model-wide parameters.

Afterwards, SubmodelGenerators should make SpeciesTypes that aren't explicit in the kb, Observables, reactions, and rate laws for the reactions, and submodel-specific parameters. We plan to make Species a separate obj_model.model (so that they're available for Observables). when that happens Species will be made here too.

**Comment by balazs1987** [comment]
done
